name: CI
on:
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: yarn
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Create env file
        run: |
          touch .env
          echo HYGRAPH_API=${{ secrets.HYGRAPH_API }} >> .env
      - name: Generate TypeScript codes from GraphQL
        run: yarn generate
      - name: Lint
        run: yarn lint
      - name: Production build
        run: yarn build
